--- #YAML:1.0
name:                Catalyst-Plugin-Authorization-Roles
version:             0.06
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Catalyst:                      5.49
    Catalyst::Plugin::Authentication: 0.10003
    Set::Object:                   1.14
    Test::Exception:               0
    UNIVERSAL::isa:                0.05
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
